# ==============================================================================
# Generated by qmake (2.01a) (Qt 4.6.3) on: Wed Feb 23 16:15:07 2011
# This file is generated by qmake and should not be modified by the
# user.
#  Name        : Makefile
#  Description : Wrapper Makefile for calling Symbian build tools
#
# ==============================================================================


MAKEFILE          = Makefile
QMAKE             = c:\nokiaqtsdk\symbian\sdk\bin\qmake.exe
DEL_FILE          = del
DEL_DIR           = rmdir
MOVE              = move
CHK_DIR_EXISTS    = if not exist
MKDIR             = mkdir
XCOPY             = xcopy /d /f /h /r /y /i
ABLD              = ABLD.BAT
DEBUG_PLATFORMS   = winscw gcce armv5 armv6
RELEASE_PLATFORMS = gcce armv5 armv6
MAKE              = make

ifeq (WINS,$(findstring WINS, $(PLATFORM)))
ZDIR=$(EPOCROOT)epoc32\release\$(PLATFORM)\$(CFG)\Z
else
ZDIR=$(EPOCROOT)epoc32\data\z
endif

DEFINES	 = -DSYMBIAN -DUNICODE -DQT_KEYPAD_NAVIGATION -DQT_SOFTKEYS_ENABLED -DQT_USE_MATH_H_FLOATS -DORIENTATIONLOCK -DNETWORKACCESS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
INCPATH	 =  -I"C:/NokiaQtSDK/Symbian/SDK/include/QtCore" -I"C:/NokiaQtSDK/Symbian/SDK/include/QtCore/tmp" -I"C:/NokiaQtSDK/Symbian/SDK/include/QtGui" -I"C:/NokiaQtSDK/Symbian/SDK/include/QtGui/tmp" -I"C:/NokiaQtSDK/Symbian/SDK/include" -I"C:/NokiaQtSDK/Symbian/SDK/include/tmp" -I"C:/NokiaQtSDK/Symbian/SDK/include/QtSensors" -I"C:/NokiaQtSDK/Symbian/SDK/include/QtSensors/tmp" -I"C:/NokiaQtSDK/Symbian/SDK/mkspecs/common/symbian" -I"C:/NokiaQtSDK/Symbian/SDK/mkspecs/common/symbian/tmp" -I"C:/NokiaQtSDK/Symbian/SDK/epoc32/include" -I"C:/NokiaQtSDK/Symbian/SDK/epoc32/include/osextensions/stdapis" -I"C:/NokiaQtSDK/Symbian/SDK/epoc32/include/osextensions/stdapis/sys" -I"C:/NokiaQtSDK/Symbian/SDK/epoc32/include/stdapis" -I"C:/NokiaQtSDK/Symbian/SDK/epoc32/include/stdapis/sys" -I"C:/NokiaQtSDK/Symbian/SDK/epoc32/include/oem" -I"C:/NokiaQtSDK/Symbian/SDK/epoc32/include/middleware" -I"C:/NokiaQtSDK/Symbian/SDK/epoc32/include/domain/middleware" -I"C:/NokiaQtSDK/Symbian/SDK/epoc32/include/osextensions" -I"C:/NokiaQtSDK/Symbian/SDK/epoc32/include/domain/osextensions" -I"C:/NokiaQtSDK/Symbian/SDK/epoc32/include/domain/osextensions/loc" -I"C:/NokiaQtSDK/Symbian/SDK/epoc32/include/domain/middleware/loc" -I"C:/NokiaQtSDK/Symbian/SDK/epoc32/include/domain/osextensions/loc/sc" -I"C:/NokiaQtSDK/Symbian/SDK/epoc32/include/domain/middleware/loc/sc" -I"C:/QtSensors" -I"C:/QtSensors/tmp" -I"C:/NokiaQtSDK/Symbian/SDK/epoc32/include/osextensions/stdapis/stlport" -I"C:/NokiaQtSDK/Symbian/SDK/epoc32/include/stdapis/stlport" -I"C:/QtProjects/DiceRollMobile/moc" -I"C:/QtProjects/DiceRollMobile/moc/tmp" -I"C:/QtProjects/DiceRollMobile/ui" -I"C:/QtProjects/DiceRollMobile/ui/tmp" -I"C:/QtProjects/DiceRollMobile" -I"C:/QtProjects/DiceRollMobile/tmp"
first: default
default: debug-winscw
all: debug release

qmake:
	$(QMAKE) -spec symbian-abld -o "bld.inf" "C:/QtProjects/DiceRollMobile/DiceRollMobile.pro"

bld.inf:
	$(QMAKE)

$(ABLD): bld.inf
	bldmake bldfiles

debug: $(ABLD)
	$(ABLD) build winscw udeb
	$(ABLD) build gcce udeb
	$(ABLD) build armv5 udeb
	$(ABLD) build armv6 udeb

release: $(ABLD)
	$(ABLD) build gcce urel
	$(ABLD) build armv5 urel
	$(ABLD) build armv6 urel

debug-winscw: $(ABLD)
	$(ABLD) build winscw udeb
debug-gcce: $(ABLD)
	$(ABLD) build gcce udeb
debug-armv5: $(ABLD)
	$(ABLD) build armv5 udeb
debug-armv6: $(ABLD)
	$(ABLD) build armv6 udeb
release-gcce: $(ABLD)
	$(ABLD) build gcce urel
release-armv5: $(ABLD)
	$(ABLD) build armv5 urel
release-armv6: $(ABLD)
	$(ABLD) build armv6 urel

export: $(ABLD)
	$(ABLD) export

cleanexport: $(ABLD)
	$(ABLD) cleanexport

check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_mifconv_make_all: ${ZDIR}\resource\apps\DiceRollMobile.mif
compiler_mifconv_clean:
	-$(DEL_FILE) ${ZDIR}\resource\apps\DiceRollMobile.mif 2> NUL
${ZDIR}\resource\apps\DiceRollMobile.mif: DiceRollMobile.svg 
	mifconv ${ZDIR}\resource\apps\DiceRollMobile.mif /c32 DiceRollMobile.svg

compiler_moc_header_make_all: moc\moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc\moc_mainwindow.cpp 2> NUL
moc\moc_mainwindow.cpp: mainwindow.h
	C:\NokiaQtSDK\Symbian\SDK\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN mainwindow.h -o moc\moc_mainwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp 2> NUL
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui\ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui\ui_mainwindow.h 2> NUL
ui\ui_mainwindow.h: mainwindow.ui
	c:\NokiaQtSDK\Symbian\SDK\bin\uic.exe mainwindow.ui -o ui\ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_mifconv_clean compiler_moc_header_clean compiler_uic_clean 

create_temps:
	-@ if NOT EXIST "C:\NokiaQtSDK\Symbian\SDK\include\QtCore\tmp" mkdir "C:\NokiaQtSDK\Symbian\SDK\include\QtCore\tmp"
	-@ if NOT EXIST "C:\NokiaQtSDK\Symbian\SDK\include\QtGui\tmp" mkdir "C:\NokiaQtSDK\Symbian\SDK\include\QtGui\tmp"
	-@ if NOT EXIST "C:\NokiaQtSDK\Symbian\SDK\include\tmp" mkdir "C:\NokiaQtSDK\Symbian\SDK\include\tmp"
	-@ if NOT EXIST "C:\NokiaQtSDK\Symbian\SDK\include\QtSensors\tmp" mkdir "C:\NokiaQtSDK\Symbian\SDK\include\QtSensors\tmp"
	-@ if NOT EXIST "C:\NokiaQtSDK\Symbian\SDK\mkspecs\common\symbian\tmp" mkdir "C:\NokiaQtSDK\Symbian\SDK\mkspecs\common\symbian\tmp"
	-@ if NOT EXIST "C:\QtSensors\tmp" mkdir "C:\QtSensors\tmp"
	-@ if NOT EXIST "C:\QtProjects\DiceRollMobile\moc\tmp" mkdir "C:\QtProjects\DiceRollMobile\moc\tmp"
	-@ if NOT EXIST "C:\QtProjects\DiceRollMobile\ui\tmp" mkdir "C:\QtProjects\DiceRollMobile\ui\tmp"
	-@ if NOT EXIST "C:\QtProjects\DiceRollMobile\tmp" mkdir "C:\QtProjects\DiceRollMobile\tmp"

extension_clean: compiler_clean
	-@ if EXIST "C:\NokiaQtSDK\Symbian\SDK\include\QtCore\tmp" rmdir  /S /Q  "C:\NokiaQtSDK\Symbian\SDK\include\QtCore\tmp"
	-@ if EXIST "C:\NokiaQtSDK\Symbian\SDK\include\QtGui\tmp" rmdir  /S /Q  "C:\NokiaQtSDK\Symbian\SDK\include\QtGui\tmp"
	-@ if EXIST "C:\NokiaQtSDK\Symbian\SDK\include\tmp" rmdir  /S /Q  "C:\NokiaQtSDK\Symbian\SDK\include\tmp"
	-@ if EXIST "C:\NokiaQtSDK\Symbian\SDK\include\QtSensors\tmp" rmdir  /S /Q  "C:\NokiaQtSDK\Symbian\SDK\include\QtSensors\tmp"
	-@ if EXIST "C:\NokiaQtSDK\Symbian\SDK\mkspecs\common\symbian\tmp" rmdir  /S /Q  "C:\NokiaQtSDK\Symbian\SDK\mkspecs\common\symbian\tmp"
	-@ if EXIST "C:\QtSensors\tmp" rmdir  /S /Q  "C:\QtSensors\tmp"
	-@ if EXIST "C:\QtProjects\DiceRollMobile\moc\tmp" rmdir  /S /Q  "C:\QtProjects\DiceRollMobile\moc\tmp"
	-@ if EXIST "C:\QtProjects\DiceRollMobile\ui\tmp" rmdir  /S /Q  "C:\QtProjects\DiceRollMobile\ui\tmp"
	-@ if EXIST "C:\QtProjects\DiceRollMobile\tmp" rmdir  /S /Q  "C:\QtProjects\DiceRollMobile\tmp"

pre_targetdeps: \
	generated_sources \
	all_source_deps \
	${ZDIR}\resource\apps\DiceRollMobile.mif \
	ui\ui_mainwindow.h

generated_sources: \
	moc\moc_mainwindow.cpp

all_source_deps: \
	mainwindow.h \
	ui\ui_mainwindow.h

finalize:

winscw_deployment:

winscw_deployment_clean:

deployment:

deployment_clean:

-include .make.cache

sis:
	$(if $(wildcard DiceRollMobile_template.pkg),$(if $(wildcard .make.cache),$(MAKE) -s -f $(MAKEFILE) ok_sis,$(if $(QT_SIS_TARGET),$(MAKE) -s -f $(MAKEFILE) ok_sis,$(MAKE) -s -f $(MAKEFILE) fail_sis_nocache)),$(MAKE) -s -f $(MAKEFILE) fail_sis_nopkg)

ok_sis:
	createpackage.bat $(QT_SIS_OPTIONS) DiceRollMobile_template.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

DiceRollMobile.sis:
	$(MAKE) -s -f $(MAKEFILE) sis

stub_sis:
	$(if $(wildcard DiceRollMobile_template.pkg),$(if $(wildcard .make.cache),$(MAKE) -s -f $(MAKEFILE) ok_stub_sis,$(if $(QT_SIS_TARGET),$(MAKE) -s -f $(MAKEFILE) ok_stub_sis,$(MAKE) -s -f $(MAKEFILE) fail_sis_nocache)),$(MAKE) -s -f $(MAKEFILE) fail_sis_nopkg)

ok_stub_sis:
	createpackage.bat -s $(QT_SIS_OPTIONS) DiceRollMobile_template.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

installer_sis: DiceRollMobile.sis
	$(if $(wildcard DiceRollMobile_installer.pkg),$(MAKE) -s -f $(MAKEFILE) ok_installer_sis,$(MAKE) -s -f $(MAKEFILE) fail_sis_nopkg)

ok_installer_sis: 
	createpackage.bat $(QT_SIS_OPTIONS) DiceRollMobile_installer.pkg - $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

fail_sis_nopkg:
	$(error PKG file does not exist, 'sis' and 'installer_sis' target are only supported for executables or projects with DEPLOYMENT statement)

fail_sis_nocache:
	$(error Project has to be built or QT_SIS_TARGET environment variable has to be set before calling 'SIS' target)

store_build:
	@echo # ============================================================================== > .make.cache
	@echo # This file is generated by make and should not be modified by the user >> .make.cache
	@echo #  Name        : .make.cache >> .make.cache
	@echo #  Part of     : DiceRollMobile >> .make.cache
	@echo #  Description : This file is used to cache last build target for >> .make.cache
	@echo #                make sis target. >> .make.cache
	@echo #  Version     :  >> .make.cache
	@echo # >> .make.cache
	@echo # ============================================================================== >> .make.cache
	@echo. >> .make.cache
	@echo QT_SIS_TARGET ?= $(QT_SIS_TARGET) >> .make.cache

dodistclean:
	-@ if EXIST "c:\QtProjects\DiceRollMobile\DiceRollMobile_template.pkg" $(DEL_FILE)  "c:\QtProjects\DiceRollMobile\DiceRollMobile_template.pkg"
	-@ if EXIST "c:\QtProjects\DiceRollMobile\DiceRollMobile_installer.pkg" $(DEL_FILE)  "c:\QtProjects\DiceRollMobile\DiceRollMobile_installer.pkg"
	-@ if EXIST "c:\QtProjects\DiceRollMobile\Makefile" $(DEL_FILE)  "c:\QtProjects\DiceRollMobile\Makefile"
	-@ if EXIST "c:\QtProjects\DiceRollMobile\Makefile_0xE11A5D0A.mk" $(DEL_FILE)  "c:\QtProjects\DiceRollMobile\Makefile_0xE11A5D0A.mk"
	-@ if EXIST "c:\QtProjects\DiceRollMobile\DiceRollMobile_0xE11A5D0A.mmp" $(DEL_FILE)  "c:\QtProjects\DiceRollMobile\DiceRollMobile_0xE11A5D0A.mmp"
	-@ if EXIST "c:\QtProjects\DiceRollMobile\DiceRollMobile_reg.rss" $(DEL_FILE)  "c:\QtProjects\DiceRollMobile\DiceRollMobile_reg.rss"
	-@ if EXIST "c:\QtProjects\DiceRollMobile\DiceRollMobile.rss" $(DEL_FILE)  "c:\QtProjects\DiceRollMobile\DiceRollMobile.rss"
	-@ if EXIST "c:\QtProjects\DiceRollMobile\DiceRollMobile.loc" $(DEL_FILE)  "c:\QtProjects\DiceRollMobile\DiceRollMobile.loc"
	-@ if EXIST "c:\QtProjects\DiceRollMobile\.make.cache" $(DEL_FILE)  "c:\QtProjects\DiceRollMobile\.make.cache"
	-@ if EXIST "c:\QtProjects\DiceRollMobile\bld.inf" $(DEL_FILE)  "c:\QtProjects\DiceRollMobile\bld.inf"

distclean: clean dodistclean

clean: $(ABLD)
	-$(ABLD) reallyclean
	-bldmake clean

clean-debug: $(ABLD)
	$(ABLD) reallyclean winscw udeb
	$(ABLD) reallyclean gcce udeb
	$(ABLD) reallyclean armv5 udeb
	$(ABLD) reallyclean armv6 udeb

clean-release: $(ABLD)
	$(ABLD) reallyclean gcce urel
	$(ABLD) reallyclean armv5 urel
	$(ABLD) reallyclean armv6 urel

clean-debug-winscw: $(ABLD)
	$(ABLD) reallyclean winscw udeb
clean-debug-gcce: $(ABLD)
	$(ABLD) reallyclean gcce udeb
clean-debug-armv5: $(ABLD)
	$(ABLD) reallyclean armv5 udeb
clean-debug-armv6: $(ABLD)
	$(ABLD) reallyclean armv6 udeb
clean-release-gcce: $(ABLD)
	$(ABLD) reallyclean gcce urel
clean-release-armv5: $(ABLD)
	$(ABLD) reallyclean armv5 urel
clean-release-armv6: $(ABLD)
	$(ABLD) reallyclean armv6 urel

run:
	-call /NokiaQtSDK/Symbian/SDK/epoc32/release/winscw/udeb/DiceRollMobile.exe $(QT_RUN_OPTIONS)
runonphone: sis
	runonphone $(QT_RUN_ON_PHONE_OPTIONS) --sis DiceRollMobile.sis DiceRollMobile.exe $(QT_RUN_OPTIONS)

