import Qt 4.7

Image {
    id: board

    property real accX
    property real accY
    property real accZ

    // signaled just as the player initiates movement input (start rolling)
    signal calibrate()

    // functions are used as Qt slots when acceleromter changes
    function updateX(outVX) {
        board.accX = outVX
    }
    function updateY(outVY) {
        board.accY = outVY
    }
    function updateZ(outVZ) {
        board.accZ = outVZ
    }

    anchors.fill: parent
    source: "board.png"
    smooth: true

    MouseArea {
        anchors.fill: parent
        onClicked: {
            //do something
        }
    }

    Image {
        id: d6
        x: 626
        y: 78
        width: 75
        height: 75
        smooth: true
        source: "d6.png"

        Text {
            id: d6Num
            x: 20
            y: 27
            color: "#45c3c3"
            text: "6" //to be a random, generated by movement
            anchors.centerIn: parent
            horizontalAlignment: Text.AlignHCenter
            styleColor: "#000000"
            style: Text.Sunken
            font.bold: true
            font.pixelSize: 18
        }
    }

    Text {
        id:xLabel
        x: 395
        y: 137
        color: "#45c3c3"
        text: "X Accereration: " + board.accX
        anchors.verticalCenterOffset: -92
        anchors.horizontalCenterOffset: 1
        anchors.centerIn: parent
        horizontalAlignment: Text.AlignLeft
        styleColor: "#000000"
        style: Text.Sunken
        font.bold: true
        font.pixelSize: 18
    }


    Text {
        id:yLabel
        x: 395
        y: 212
        color: "#45c3c3"
        text: "Y Accereration: " + board.accY
        anchors.verticalCenterOffset: -17
        anchors.horizontalCenterOffset: 1
        anchors.centerIn: parent
        horizontalAlignment: Text.AlignLeft
        styleColor: "#000000"
        style: Text.Sunken
        font.bold: true
        font.pixelSize: 18
    }

    Text {
        id:zLabel
        x: 395
        y: 282
        color: "#45c3c3"
        text: "Z Accereration: " + board.accZ
        anchors.verticalCenterOffset: 53
        anchors.horizontalCenterOffset: 1
        anchors.centerIn: parent
        horizontalAlignment: Text.AlignLeft
        styleColor: "#000000"
        style: Text.Sunken
        font.bold: true
        font.pixelSize: 18
    }
}
